<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="2" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="CalcTest" duration-ms="19" started-at="2016-07-14T13:20:53Z" finished-at="2016-07-14T13:20:53Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="19" started-at="2016-07-14T13:20:53Z" finished-at="2016-07-14T13:20:53Z">
      <class name="CalcTest">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:CalcTest@48140564]" name="beforeSuite" is-config="true" duration-ms="10" started-at="2016-07-14T16:20:53Z" finished-at="2016-07-14T16:20:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:CalcTest@48140564]" name="beforeTest" is-config="true" duration-ms="0" started-at="2016-07-14T16:20:53Z" finished-at="2016-07-14T16:20:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:CalcTest@48140564]" name="beforeClass" is-config="true" duration-ms="0" started-at="2016-07-14T16:20:53Z" finished-at="2016-07-14T16:20:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:CalcTest@48140564]" name="setUp" is-config="true" duration-ms="1" started-at="2016-07-14T16:20:53Z" finished-at="2016-07-14T16:20:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testNullPointerException()[pri:0, instance:CalcTest@48140564]" name="testNullPointerException" duration-ms="2" started-at="2016-07-14T16:20:53Z" finished-at="2016-07-14T16:20:53Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at CalcTest.testNullPointerException(CalcTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNullPointerException -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:CalcTest@48140564]" name="tearDown" is-config="true" duration-ms="1" started-at="2016-07-14T16:20:53Z" finished-at="2016-07-14T16:20:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="testSum()[pri:0, instance:CalcTest@48140564]" name="testSum" duration-ms="3" started-at="2016-07-14T16:20:53Z" finished-at="2016-07-14T16:20:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSum -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:CalcTest@48140564]" name="setUp" is-config="true" duration-ms="0" started-at="2016-07-14T16:20:53Z" finished-at="2016-07-14T16:20:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:CalcTest@48140564]" name="tearDown" is-config="true" duration-ms="1" started-at="2016-07-14T16:20:53Z" finished-at="2016-07-14T16:20:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:CalcTest@48140564]" name="afterClass" is-config="true" duration-ms="0" started-at="2016-07-14T16:20:53Z" finished-at="2016-07-14T16:20:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:CalcTest@48140564]" name="afterTest" is-config="true" duration-ms="0" started-at="2016-07-14T16:20:53Z" finished-at="2016-07-14T16:20:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:CalcTest@48140564]" name="afterSuite" is-config="true" duration-ms="0" started-at="2016-07-14T16:20:53Z" finished-at="2016-07-14T16:20:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- CalcTest -->
    </test> <!-- Command line test -->
  </suite> <!-- CalcTest -->
</testng-results>
